FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Majestic Thai

Polls is a simple API allowing consumers to view polls and vote in them.

## Dishes Collection [/dishes]

### List Menu Items [GET]

+ Response 200 (application/json)

           [
            {   "id":101,
                "dish": "Yellow Curry",
                "price": "10.95",
                "description": "Mild yellow curry, containing rich flavors of curry powder, coconut milk, potatoes, onions and carrots."
            },
            {   "id":102,
                "dish": "Pad Thai",
                "price": "10.95",
                "description": "One of the most famous Thai rice noodles dish cooked with egg, bean spouts, tofu and sprinkled with ground peanut."
            },
            {   "id":103,
                "dish": "Orange Chicken",
                "price": "10.95",
                "description": "Deep fried chicken sauteed in a tangy orange sauce."
            }
        ]
        
## Dishes Collection [/dishes/:id]

+ Parameters
    + id(number) - ID of the Dish in the form of an integer
    

###List Menu Items [GET]
    
+ Response 200 (application/json)

        [ 
            {   "id":101,
                "dish": "Yellow Curry",
                "price": "10.95",
                "description": "Mild yellow curry, containing rich flavors of curry powder, coconut milk, potatoes, onions and carrots."
            }
        ]

## List of Orders [/orders]

###List of Order Items [GET]

+ Response 200 (application/json)


 [
            {
                "orderid":1,
                "time": "3:12 pm",
                "total": 28.85,
                "items":[
                            {   "id":7,
                                "dish": "Yellow Curry",
                                "price": "10.95",
                                "description": "Minced chicken tossed with lime juice, chili paste, onion, basil leaf, roasted rice powder, cilantro, and mixed greens"
                            },
                             {   "id":8,
                                "dish": "Pad Thai",
                                "price": "10.95",
                                "description": "One of the most famous Thai rice noodles dish cooked with egg, bean spouts, tofu and sprinkled with ground peanut."
                            },
                            {   
                                "id":1,
                                "dish": "Orange Chicken",
                                "price": "10.95",
                                "description": "Deep fried chicken sauteed in a tangy orange sauce."
                            }
                        ]
            },
            {
                "orderid":2,
                "time": "4:32 pm",
                "total": 22.85,
                "items":[
                           {   "id":7,
                                "dish": "Yellow Curry",
                                "price": "10.95",
                                "description": "Minced chicken tossed with lime juice, chili paste, onion, basil leaf, roasted rice powder, cilantro, and mixed greens"
                            },
                             {   "id":8,
                                "dish": "Pad Thai",
                                "price": "10.95",
                                "description": "One of the most famous Thai rice noodles dish cooked with egg, bean spouts, tofu and sprinkled with ground peanut."
                            },
                            {   
                                "id":1,
                                "dish": "Orange Chicken",
                                "price": "10.95",
                                "description": "Deep fried chicken sauteed in a tangy orange sauce."
                            }
                        ]
            }
        ]

## List of Orders [/orders/3]

###List of Order Items [GET]

+ Response 200 (application/json)


 [
            {
                "orderid":1,
                "time": "3:12 pm",
                "total": 28.85,
                "items":[
                            {   "id":7,
                                "dish": "Yellow Curry",
                                "price": "10.95",
                                "description": "Minced chicken tossed with lime juice, chili paste, onion, basil leaf, roasted rice powder, cilantro, and mixed greens"
                            },
                             {   "id":8,
                                "dish": "Pad Thai",
                                "price": "10.95",
                                "description": "One of the most famous Thai rice noodles dish cooked with egg, bean spouts, tofu and sprinkled with ground peanut."
                            },
                            {   
                                "id":1,
                                "dish": "Orange Chicken",
                                "price": "10.95",
                                "description": "Deep fried chicken sauteed in a tangy orange sauce."
                            }
                        ]
            }
    ]